# Usa imagem base do Nginx
FROM nginx:alpine

# Remove arquivos padrão
RUN rm -rf /usr/share/nginx/html/*

# Copia os arquivos da pasta dist do React
COPY dist/ /usr/share/nginx/html

# Copia o arquivo de configuração do Nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expõe a porta 80 (HTTP padrão)
EXPOSE 4001

# Comando padrão do Nginx
CMD ["nginx", "-g", "daemon off;"]
