version: '3.8'

services:
  backend-nf:
    container_name: backend-nf
    build: backend/.
    ports:
      - "3000:3000"
  
  frontend-nf:
    container_name: frontend-nf
    build: frontend/.
    ports:
      - "8080:8080"
      - "4001:4001"
    depends_on:
      - backend-nf